### ISSUE TITLE
Typescript: tap returns promise, errors in runEffects

### ISSUE THREAD

**Issue by janat08** [mostjs/core#278] opened 2019-03-29 21:37 UTC
runEffects expects a stream, and tap returns a promise, therefore types don't match although they're meant for each other.

**Comment by briancavalier** [comment] 2019-03-30 01:07
Hi @janat08.  [Here is the TS type of `tap`](https://github.com/mostjs/core/blob/master/packages/core/type-definitions/combinator/transform.d.ts#L6-L7), which returns a stream.  [Here is the implementation of `tap`](https://github.com/mostjs/core/blob/master/packages/core/src/combinator/transform.js#L34).  It returns a `Tap`, which implements the [Stream interface](https://mostcore.readthedocs.io/en/latest/api.html#stream).

Can you please provide a [TS code sandbox](https://codesandbox.io/s/vanilla-ts) or complete example code that reproduces the issue you're seeing?  Thanks!

**Comment by janat08** [comment] 2019-03-30 01:15
https://codesandbox.io/s/r07qyv4n3p?fontsize=14
I believe it's suppose to install the packages itself, according to the documentation.

**Comment by briancavalier** [comment] 2019-03-30 01:55
Thanks for creating a codesandbox 👍   That helps a lot.

The issue in the example is not that tap returns a Promise.  The type error is indicating that this line isn't using the `@most/core` API correctly:

```typescript
      until(events, runEffects(tapped, newDefaultScheduler()));
``` 

That's a good thing!  It's an opportunity to learn from the types.  I hope you'll bear with me, as we dig in a bit.

If you hover over `tapped`, you'll see that it's type is `MostStream<any>`, so it's a `@most/core` stream.  If you look at the type of [`runEffects`](https://github.com/mostjs/core/blob/master/packages/core/type-definitions/runEffects.d.ts#L3), you'll find that it _returns_ a Promise.  And finally, if you look at the type of [`until`](https://github.com/mostjs/core/blob/master/packages/core/type-definitions/combinator/timeslice.d.ts#L3), you'll see that it accepts 2 Streams.  So, we can refactor the line above by extracting a variable, it makes the types easier to see:

```typescript
   const promise: Promise<void> = runEffects(tapped, newDefaultScheduler())
   until(events, promise)
```

So, those types clearly don't line up: `until` expects a stream, so we can't pass a promise to it.

I'll say a few words about `@most/core`'s general philosophy and mechanics, a few things about combinators, such as `tap` and `until`, and finally a bit about `runEffects`.  I'd also suggest taking a look at some [examples](https://github.com/mostjs/core/tree/master/examples), to get a feel for these things.

### Philosophy and mechanics

`@most/core` streams are inert until observed with runEffects.  You program with them by using declarative API functions like `map`, `until`, `merge` etc. to build a big "machine" that _will do_ what you need.  The goal is to end up with a single stream that represents the whole computation over time that you need.

#### runEffects

After you've built the machine, that is, a big graph of streams, now represented by a single, final stream, you unleash it by calling `runEffects` with a Scheduler that provides the shared notion of time for the whole graph.

In the usual case, there should be exactly 1 call to runEffects as the last function call.  Build up declaratively, then finally, activate.  So, if you find yourself reaching for `runEffects` at various places, that's probably a sign that you're fighting the architecture rather than working with it.

This can be a different way of thinking, and one may wonder if it's possible to build anything real in this way.  [Here's TodoMVC built in exactly this way](https://github.com/briancavalier/mostcore-todomvc/blob/master/src/index.js#L33).  Again, it can be a different way of approaching problems and solutions, but it can be quite pleasant and effective once you get the hang of it.

I hope that helps.  Again, I think it will be helpful to read some of the simple [examples](https://github.com/mostjs/core/tree/master/examples) and the [TodoMVC example](https://github.com/briancavalier/mostcore-todomvc/tree/master/src).

**Comment by janat08** [comment] 2019-03-30 02:09
Well I take issue with runEffects returning promise, it may as well just return never().

**Comment by janat08** [comment] 2019-03-30 02:09
or frompromise if it actually tries to resolve things first.

**Comment by janat08** [comment] 2019-03-30 02:13
If you're building a widget or something the machine may have to stop prematurely before browser trashes everything.

**Comment by briancavalier** [comment] 2019-03-30 02:24
I respect that you disagree with the philosophy.  You're certainly free to, and to use other libraries.  If you decide to invest time in learning the benefits of the architecture, we'll be here to help.

I'll close this, since the the original issue was the perception that tap returns a promise, and we've seen that it returns a stream.

**Closed by briancavalier** 2019-03-30 02:24 UTC

**Comment by janat08** [comment] 2019-03-30 02:42
The github or docs themselves advertise using runeffects with until.

**Comment by janat08** [comment] 2019-03-30 02:43
I assume that it's only a type mistmach, with it working as expected?

**Comment by janat08** [comment] 2019-03-30 02:51
or rather advertise using it with run.
