### ISSUE TITLE
unsubscribe equivalent

### ISSUE THREAD

**Issue by cezl** [mostjs/core#266] opened 2019-01-31 03:52 UTC
Hi guys!
I was wondering if the @most/core has some sort of unsubscribe mechanism like most.js (cujojs) and RxJS. The closest operation to subscribe is run, but run (taking into consideration the similarities between Sink and observer), as specified in the docs, returns void. I'm asking that since I'm developing a project that allows to set (and afterwards to cancel/unsubscribe) a stream dynamically. I remember to have read in some place that @most/core avoids imperatives constructs and such, so what would be the alternative?

**Comment by cezl** [comment] 2019-01-31 19:00
Gotcha!
If that's the case, **I think** I could mix a [most-subject](https://github.com/mostjs-community/subject) subject with the combinator until in case I still want to manage the stream in a kind of imperative way :sweat_smile:

**Comment by briancavalier** [comment] 2019-01-31 19:11
Yes, absolutely.  One good general strategy is to represent the condition(s) under which disposal should occur as an event stream.  Then you can use `until`.  Of course, there are still use cases where `run`+`Disposable` may turn out to be the simplest thing :). Use your judgement, and feel free to discuss in [gitter](https://gitter.im/cujojs/most).

Recently, we've started recommending the newer [`@most/adapter`](https://github.com/mostjs/adapter) over `most-subject`.  If you go that route, be sure to check it out.

I feel like we've answered the original question of unsubscribe alternatives, so I'm going to close the issue. Please feel free to reopen if you feel there's a part of that original question that remains unanswered, and please do feel free to join us in gitter.  Thanks again for pointing out the documentation bug!

**Closed by briancavalier** 2019-01-31 19:11 UTC

**Comment by cezl** [comment] 2019-01-31 20:01
hey @briancavalier, I have one more question.
First, I have accomplished what I wanted through the @most/adapter (I suggested most-subject first because I've only looked at the packages listed on [mostjs-community](https://github.com/mostjs-community)).
Second, while testing the following code with @most/adapter on Node.js, something called my attention:
```Javascript
const [induce, events] = createAdapter();

run({event: function(time, value){
    console.log(value);
},
error: function(time, error){
    console.error(error);
}, end: function(time){
    console.log('ended');
}}, newDefaultScheduler(), until(events, periodic(500)));

setInterval(()=> {
    induce(undefined);
}, 1550);
```
After the induce function run, the program didn't ended/stopped as I was expecting. For instance, the following code in RxJS would terminate the program as soon as the second interval emitted:
```Javascript
interval(500).pipe(takeUntil(interval(1550))).subscribe(console.log);
```
Is that an expected behavior? Should the programmer call process.exit() (Node.js) manually in that case?

**Comment by briancavalier** [comment] 2019-01-31 22:52
@cezl Thanks for the example.  This is indeed a subtle bug between `run` and `until`, which doesn't occur with `runEffects`.  Since `run` gets far less use, afaik, we've not seen the bug before.  I'm sorry you hit it, but thank you for finding it!  Your example was very helpful in reproducing it.

A candidate fix is in #270.  You can try the [fix-until-dispose branch](https://github.com/mostjs/core/tree/fix-until-dispose) if you'd like.

As I was using your example to reproduce, I wrote a few variations of it.  I figure they might be helpful to you since you may still be adjusting to differences between most/core and rxjs.

The first one is very similar to your original:

```js
const [induce, events] = createAdapter();

run({
  event: (time, value) => console.log(value),
  error: (time, error) => console.error(error),
  end: (time) => console.log('ended')
}, newDefaultScheduler(), until(events, periodic(500)));

setTimeout(induce, 1550)
```

If I were writing the declarative equivalent, here's how I'd do it:

```js
const events = until(at(1550), tap(console.log, periodic(500)))

runEffects(events, newDefaultScheduler())
  .then(() => console.log('ended'), e => console.error(e))
```

Cheers!

**Comment by briancavalier** [comment] 2019-02-01 11:32
> the project I'm working on demands some sort of interoperability between most.js and RxJS

Ah, cool.

> don't have to even use the until to come across that bug

I think in this case, the problem is `setInterval`, which runs forever.  You can see it by adding a console.log in the interval callback:

```js
setInterval(()=> {
   disposable.dispose();
   console.log('interval');
}, 1550);
```

Switching to `setTimeout` allows node to exit, even without #270.

```js
const d = run({
  event: (time, value) => console.log(value),
  error: (time, error) => console.error(error),
  end: (time) => console.log('ended')
}, newDefaultScheduler(), periodic(500));

setTimeout(() => d.dispose(), 1550);
```

Also, just a quick note that explicit disposal is immediate and forceful.  For example, it's correct that "ended" is not logged.

**Comment by cezl** [comment] 2019-02-01 13:03
> Switching to setTimeout allows node to exit, even without #270.

Damn it. My fault :sweat_smile: Sorry!

Anyway, correcting my first example for timeout
```Javascript
const [induce, events] = createAdapter();

run({event: function(time, value){
    console.log(value);
}, error: function(time, error){
    console.error(error);
}, end: function(time){
    console.log('ended');
}}, newDefaultScheduler(), until(events, periodic(500)));

setTimeout(()=> {
    induce(undefined);
}, 1550);
```
indeed hangs the program (relieved) :sweat_smile:

> Also, just a quick note that explicit disposal is immediate and forceful. For example, it's correct that "ended" is not logged.

Yep. It's just like an unsubscribe (:

**Comment by briancavalier** [comment] 2019-02-01 16:42
Just publish `@most/core` 1.3.3 and `@most/scheduler` 1.2.2, which have the fix for the `until`+`run` issue.  Let us know if they work for you.

Thanks again for all the discussion and examples that helped us find and fix the bug!

**Comment by cezl** [comment] 2019-02-01 18:41
Yep, now it's working as expected :raised_hands:

> Thanks again for all the discussion and examples that helped us find and fix the bug!

My pleasure! (:
